# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the TypeScript application
RUN npm run build

# Stage 2: Run
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy built files and necessary runtime files
COPY --from=builder /app/dist ./dist
COPY package.json package-lock.json ./

# Install production dependencies
RUN npm install --production

# Copy the .env file
COPY .env.example .env

# Expose the port the app runs on
EXPOSE 5173

# Start the application
CMD ["node", "dist/index.js"]
